
config:
  notifiers:
    smtp:
      format: "html"
      from: "XXXXXX"
      hostPort: "XXXXXX:XXX"
      password: "XXXXXX"
      tls: false
      to: "XXXXX@XXXXXX"
      user: "XXXXXX"


  defaultNotifiers:
      - k8sevents
      - smtp
    
  watchRules: true

  rulesOverride: |
    - rule: Leitura ou Escrita em /tmp/flag
      description: Foi efetuado uma Leitura ou Escrita no arquivo /tmp/flag
      match:
        rules:
          - Leitura ou Escrita em /tmp/flag
        output_fields:
          - k8s.ns.name!=kube-system, k8s.ns.name!=falco
      actions:
        - action: Terminate Pod