name: Trabalho
run-name: ${{ github.actor }}  
on: [push]
jobs:
  CID-Pipeline:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t trabalhodefesa:1.0 .
      
      - name: Run Dockle Scan
        uses: erzz/dockle-action@v1
        with:
          image: trabalhodefesa:1.0
          args: "--severity FATAL --exclude CIS-DI-0005 --exclude CIS-DI-0006 --exclude CIS-DI-0008"
          exit-code: 1  # Fail the pipeline if issues are found