name: Trabalho
run-name: ${{ github.actor }}  
on: [push]
jobs:
  CID-Pipeline:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t cel0/trabalhodefesa:1.0 .
      
      - name: Run Dockle Scan
        uses: goodwithtech/dockle-action@main
        with:
          image: 'celo0/trabalhodefesa:1.0'
          format: 'list'
          exit-code: '1'
          exit-level: 'fatal'
          ignore: 'CIS-DI-0001,DKL-DI-0006,CIS-DI-0005,CIS-DI-0006,CIS-DI-0008'
